- name: copy war file
  copy: src=/var/lib/jenkins/workspace/CICDusingAnsible/target/CICDusingAnsible-1.war dest=/var/lib/tomcat9/webapps/LTI.war
  
- name: Stop tomcat
  service:
    name: tomcat
    state: restarted
    enabled: yes
